name: Manual Runner

on:
  workflow_dispatch:
    inputs:
        consent:
                    default: 'Type here...'
                    description: 'Are you sure you want to automatically unfollow and follow people? (Type Yes or No)'
                    required: true
                    type: string
jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: Verify installation
        run: |
          python -m pip show requests
      - name: Run Python file
        env:
          Graphql_Token: ${{ secrets.Graphql_Token }}
          Exceptions_follow: ${{ secrets.Exceptions_follow }}
          Exceptions_following: ${{ secrets.Exceptions_following }}
          Consent: ${{ inputs.consent}}
        run: |
          python main.py
